【20週まで】17-19週のつもりが20週まで提出します
posse-ap/gen2.0-mirei1115 pull request #8
Opened 2022-06-21 06:01 UTC by mirei1115

## 今週の課題
第17週
- [ ] Dockerをインストールしましたか？
- [ ] DockerでNginxコンテナを起動しましたか？
第18週
- [ ] ブラウザで「http://localhost」にアクセスすると自作したQuizyが表示されましたか？
第19週
- [ ] Dockerでphpが動作するコンテナを起動しましたか？
第20週
- [ ] ブラウザで「http://localhost」にアクセスするとphpinfo();関数の結果が表示されましたか？

## 注意点やレビュワーに伝えたいこと(あれば)

## 課題が終わっている証跡(スクショ)
![スクリーンショット (838)](https://user-images.githubusercontent.com/86916710/174727121-dcf38f23-a4ee-4678-9a8b-b9cad3036441.png)
![スクリーンショット (839)](https://user-images.githubusercontent.com/86916710/174727197-1b4e7f0c-bcc5-4e59-9a2b-1c41d789fae3.png)

2022-06-21 11:43 UTC, Mitsuru53 requested changes
🙏

2022-06-21 11:43 UTC, Mitsuru53 commented on php/Dockerfile
> +RUN pecl install xdebug && docker-php-ext-enable xdebug && \
xdebugが2つあるように見えます

2022-06-21 11:43 UTC, Mitsuru53 commented on php/Dockerfile
> +RUN curl -sSL https://github.com/mailhog/mhsendmail/releases/download/v0.2.0/mhsendmail_linux_amd64 -o mhsendmail \
コピペ形跡。不要なものを入れないようにしてください

YAGNI原則
https://e-words.jp/w/YAGNI%E5%8E%9F%E5%89%87.html

2022-06-21 11:43 UTC, Mitsuru53 commented on src/static/js/quizy.js
> +const choice = [
choicesかな

2022-06-21 11:43 UTC, Mitsuru53 commented on src/static/js/quizy.js
> +const answer = ['たかなわ','かめいど','こうじまち','おなりもん','とどろき','しゃくじい','ぞうしき','おかちまち','ししぼね','こぐれ',]
ditto

2022-06-21 11:43 UTC, Mitsuru53 commented on src/static/js/quizy.js
> +const choiceLength = 3;
定数なのでCHOCE_LENGTH

2022-06-21 11:43 UTC, Mitsuru53 commented on src/static/js/quizy.js
> +for (let quizIndex = 0; quizIndex < choice.length; quizIndex++) {
foreach使ってみてください

2022-06-21 11:43 UTC, Mitsuru53 commented on src/static/js/quizy.js
> +function check(quizIndex,choiceNum,correctNum) {
関数名が一般的すぎます
具体的な名前に変更お願いします

2022-06-22 09:33 UTC, niijima1229 reviewed
これもお願いします！

2022-06-22 09:33 UTC, niijima1229 commented on mysql/data/auto.cnf
> +[auto]
mysql/data以下をgit管理してはいけない！
.gitignoreに
`mysql/data`
を書いて
コマンドで
`git rm -rf --cached mysql/data`
を行う

2022-08-27 20:03 UTC, merged